version: "3.9"

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./auth-service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: host=postgres user=postgres password=mysecretpassword dbname=postgres port=5432 sslmode=disable
    ports:
      - "8080:8080"

  note-service:
    build:
      context: ./note-service
    depends_on:
      - postgres
      - auth-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:8080/validate
      DATABASE_URL: host=postgres user=postgres password=mysecretpassword dbname=postgres port=5432 sslmode=disable
    ports:
      - "8081:8081"